//const BACKEND_API_LOCATION = "https://localhost:4000";
const BACKEND_API_LOCATION =
  "https://shielded-bastion-15318-a461a9ee545a.herokuapp.com";
const SET_WORKOUTS = "SET_WORKOUTS";
const CREATE_WORKOUT = "CREATE_WORKOUT";
const SET_TITLE = "SET_TITLE";
const SET_LOAD = "LOAD_TITLE";
const SET_REPS = "REPS_TITLE";
const SET_ERROR = "SET_ERROR";
const SET_EDIT = "SET_EDIT";
const SET_WORKOUT = "SET_WORKOUT";
const UPDATE_LOCAL_DATA = "UPDATE_LOCAL_DATA";
const SHOW_MODAL = "SHOW_MODAL";
const HIDE_MODAL = "HIDE_MODAL";
const DELETE_LOCAL_DATA = "DELETE_LOCAL_DATA";

export {
  BACKEND_API_LOCATION,
  SET_WORKOUTS,
  CREATE_WORKOUT,
  SET_TITLE,
  SET_LOAD,
  SET_REPS,
  SET_ERROR,
  SET_EDIT,
  SET_WORKOUT,
  UPDATE_LOCAL_DATA,
  SHOW_MODAL,
  HIDE_MODAL,
  DELETE_LOCAL_DATA,
};
